version: 0.1
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=javaproject11 -Dsonar.organization=Javaproject11 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=daf717419b4182f163ba81b6ffd5fc467987978f
    
